package quickcmd

var ShortcutsCommands = []CommandItem{
	// 1. 서버 목록 (Host Explorer) 패널
	{
		ID:          "sc_host_enter",
		CategoryKey: "sc_cat_host",
		TitleKey:    "sc_host_enter_title",
		DescKey:     "sc_host_enter_desc",
		Command:     "Enter / c",
	},
	{
		ID:          "sc_host_fullscreen",
		CategoryKey: "sc_cat_host",
		TitleKey:    "sc_host_fullscreen_title",
		DescKey:     "sc_host_fullscreen_desc",
		Command:     "t",
	},
	{
		ID:          "sc_host_file",
		CategoryKey: "sc_cat_host",
		TitleKey:    "sc_host_file_title",
		DescKey:     "sc_host_file_desc",
		Command:     "f / F6",
	},
	{
		ID:          "sc_host_reconnect",
		CategoryKey: "sc_cat_host",
		TitleKey:    "sc_host_reconnect_title",
		DescKey:     "sc_host_reconnect_desc",
		Command:     "r",
	},
	{
		ID:          "sc_host_telemetry",
		CategoryKey: "sc_cat_host",
		TitleKey:    "sc_host_telemetry_title",
		DescKey:     "sc_host_telemetry_desc",
		Command:     "m / F5",
	},
	{
		ID:          "sc_host_runbook",
		CategoryKey: "sc_cat_host",
		TitleKey:    "sc_host_runbook_title",
		DescKey:     "sc_host_runbook_desc",
		Command:     "? / Ctrl+K",
	},
	{
		ID:          "sc_host_settings",
		CategoryKey: "sc_cat_host",
		TitleKey:    "sc_host_settings_title",
		DescKey:     "sc_host_settings_desc",
		Command:     "p",
	},
	{
		ID:          "sc_host_add",
		CategoryKey: "sc_cat_host",
		TitleKey:    "sc_host_add_title",
		DescKey:     "sc_host_add_desc",
		Command:     "a / n",
	},
	{
		ID:          "sc_host_edit_del",
		CategoryKey: "sc_cat_host",
		TitleKey:    "sc_host_edit_del_title",
		DescKey:     "sc_host_edit_del_desc",
		Command:     "e / d",
	},
	{
		ID:          "sc_host_quit",
		CategoryKey: "sc_cat_host",
		TitleKey:    "sc_host_quit_title",
		DescKey:     "sc_host_quit_desc",
		Command:     "q",
	},

	// 2. 원격 콘솔 (Terminal) 패널
	{
		ID:          "sc_console_esc",
		CategoryKey: "sc_cat_console",
		TitleKey:    "sc_console_esc_title",
		DescKey:     "sc_console_esc_desc",
		Command:     "Esc",
	},
	{
		ID:          "sc_console_fullscreen",
		CategoryKey: "sc_cat_console",
		TitleKey:    "sc_console_fullscreen_title",
		DescKey:     "sc_console_fullscreen_desc",
		Command:     "t",
	},
	{
		ID:          "sc_console_file",
		CategoryKey: "sc_cat_console",
		TitleKey:    "sc_console_file_title",
		DescKey:     "sc_console_file_desc",
		Command:     "Ctrl+F",
	},
	{
		ID:          "sc_console_tab_new",
		CategoryKey: "sc_cat_console",
		TitleKey:    "sc_console_tab_new_title",
		DescKey:     "sc_console_tab_new_desc",
		Command:     "Ctrl+T",
	},
	{
		ID:          "sc_console_tab_close",
		CategoryKey: "sc_cat_console",
		TitleKey:    "sc_console_tab_close_title",
		DescKey:     "sc_console_tab_close_desc",
		Command:     "Ctrl+W",
	},
	{
		ID:          "sc_console_tab_switch",
		CategoryKey: "sc_cat_console",
		TitleKey:    "sc_console_tab_switch_title",
		DescKey:     "sc_console_tab_switch_desc",
		Command:     "Alt+1~9",
	},
	{
		ID:          "sc_console_log_export",
		CategoryKey: "sc_cat_console",
		TitleKey:    "sc_console_log_export_title",
		DescKey:     "sc_console_log_export_desc",
		Command:     "Ctrl+E",
	},
	{
		ID:          "sc_console_runbook",
		CategoryKey: "sc_cat_console",
		TitleKey:    "sc_console_runbook_title",
		DescKey:     "sc_console_runbook_desc",
		Command:     "?",
	},
	{
		ID:          "sc_console_autocomplete",
		CategoryKey: "sc_cat_console",
		TitleKey:    "sc_console_autocomplete_title",
		DescKey:     "sc_console_autocomplete_desc",
		Command:     "Tab",
	},
	{
		ID:          "sc_console_interrupt",
		CategoryKey: "sc_cat_console",
		TitleKey:    "sc_console_interrupt_title",
		DescKey:     "sc_console_interrupt_desc",
		Command:     "Ctrl+C",
	},

	// 3. SFTP 파일 매니저 패널
	{
		ID:          "sc_sftp_transfer",
		CategoryKey: "sc_cat_sftp",
		TitleKey:    "sc_sftp_transfer_title",
		DescKey:     "sc_sftp_transfer_desc",
		Command:     "F5",
	},
	{
		ID:          "sc_sftp_move",
		CategoryKey: "sc_cat_sftp",
		TitleKey:    "sc_sftp_move_title",
		DescKey:     "sc_sftp_move_desc",
		Command:     "F6 / m",
	},
	{
		ID:          "sc_sftp_mkdir",
		CategoryKey: "sc_cat_sftp",
		TitleKey:    "sc_sftp_mkdir_title",
		DescKey:     "sc_sftp_mkdir_desc",
		Command:     "F7 / n",
	},
	{
		ID:          "sc_sftp_delete",
		CategoryKey: "sc_cat_sftp",
		TitleKey:    "sc_sftp_delete_title",
		DescKey:     "sc_sftp_delete_desc",
		Command:     "F8 / d",
	},
	{
		ID:          "sc_sftp_space_select",
		CategoryKey: "sc_cat_sftp",
		TitleKey:    "sc_sftp_space_select_title",
		DescKey:     "sc_sftp_space_select_desc",
		Command:     "Space",
	},
	{
		ID:          "sc_sftp_clipboard",
		CategoryKey: "sc_cat_sftp",
		TitleKey:    "sc_sftp_clipboard_title",
		DescKey:     "sc_sftp_clipboard_desc",
		Command:     "x / c / p",
	},
	{
		ID:          "sc_sftp_dotfiles",
		CategoryKey: "sc_cat_sftp",
		TitleKey:    "sc_sftp_dotfiles_title",
		DescKey:     "sc_sftp_dotfiles_desc",
		Command:     ". (dot)",
	},
	{
		ID:          "sc_sftp_inline_cmd",
		CategoryKey: "sc_cat_sftp",
		TitleKey:    "sc_sftp_inline_cmd_title",
		DescKey:     "sc_sftp_inline_cmd_desc",
		Command:     "!",
	},
	{
		ID:          "sc_sftp_runbook",
		CategoryKey: "sc_cat_sftp",
		TitleKey:    "sc_sftp_runbook_title",
		DescKey:     "sc_sftp_runbook_desc",
		Command:     "?",
	},
	{
		ID:          "sc_sftp_panel_switch",
		CategoryKey: "sc_cat_sftp",
		TitleKey:    "sc_sftp_panel_switch_title",
		DescKey:     "sc_sftp_panel_switch_desc",
		Command:     "Tab",
	},
	{
		ID:          "sc_sftp_close",
		CategoryKey: "sc_cat_sftp",
		TitleKey:    "sc_sftp_close_title",
		DescKey:     "sc_sftp_close_desc",
		Command:     "Esc",
	},
}
